UI_STRINGS = {
    "ru": {
        "start_greeting": "Привет, {name}! 👋\n\nЯ — твой проводник в мир посланий от Вселенной.\nНажми на кнопку ниже, чтобы узнать, что Вселенная хочет сказать тебе сегодня. ✨",
        "btn_get_message": "✨ Получить послание",
        "btn_personalization": "⚙️ Персонализация",
        "btn_subscription": "💎 Подписка",
        "btn_about": "✨ О проекте",
        "btn_help": "🆘 Помощь",
        "btn_language": "🌐 Language / Язык",
        "btn_open_app": "🚀 Открыть Mini App",
        "already_received_premium": "✨{name}, ты уже получил своё послание на сегодня:\n\n",
        "already_received_free": "🌌{name}, ты уже получил своё послание на сегодня. Возвращайся завтра за новым! ✨\n\n",
        "message_header": "✨{name}, твоё послание на сегодня:\n\n",
        "btn_clarify": "🔍 Разъяснить послание",
        "clarify_header": "💡 *Разъяснение:*\n\n",
        "clarify_error": "Ошибка при получении разъяснения.",
        "tarot_load_error": "Ошибка при загрузке данных Таро.",
        "tarot_card_not_found": "Ошибка: данные карты не найдены.",
        "tarot_exp_soon": "Разъяснение для этой карты скоро появится! ✨",
        "action_cancelled": "Действие отменено.",
        "main_menu": "Главное меню:",
        "zodiac_aries": "Овен", "zodiac_taurus": "Телец", "zodiac_gemini": "Близнецы", "zodiac_cancer": "Рак",
        "zodiac_leo": "Лев", "zodiac_virgo": "Дева", "zodiac_libra": "Весы", "zodiac_scorpio": "Скорпион",
        "zodiac_sagittarius": "Стрелец", "zodiac_capricorn": "Козерог", "zodiac_aquarius": "Водолей", "zodiac_pisces": "Рыбы",
        "ask_time": "Здорово, по гороскопу ты — **{zodiac}**! 🌟\n\nТеперь введи время своего рождения (например: 14:30) или нажми «Пропустить», если не знаешь:",
        "ask_region": "И последний шаг: введи свой регион или город рождения:",
        "data_saved": "Твои данные успешно сохранены! 🌟\n Теперь я знаю тебя немного лучше.",
        "sub_active": "🌟 У вас уже оформлена подписка ASTREX Premium!\n\nОна будет активна еще {days} дн.\nСпасибо, что вы с нами! ✨",
        "sub_not_active": "Нажмите на кнопку ниже, чтобы перейти к оплате через PayPal ✨",
        "payment_success": "Спасибо за уведомление об оплате! 🎉\nВаша подписка ASTREX Premium активирована на 30 дней.\nМы проверим транзакцию в ближайшее время.",
        "about_text": "✨ *ASTREX* — твой персональный проводник в мире метафизики и самопознания.\n\nМы объединяем древние знания о движении планет, цифрах и вековых традициях с современными технологиями, чтобы дарить тебе вдохновение каждый день.\n\nНаш бот поможет тебе:\n• Получать ежедневные послания от Вселенной\n• Глубже понимать свою природу через персонализированные прогнозы\n• Находить ответы на важные вопросы в нужный момент\n\nПусть каждая звезда светит именно для тебя! 🌟",
        "help_text": "🆘 *Нужна помощь?*\n\nЕсли у тебя возникли проблемы с подпиской или вопросы по работе бота, напиши в нашу службу поддержки:\n\n📩 [Связаться с поддержкой](https://t.me/astrexbotfather)\n\nМы обязательно поможем! ✨",
        "status_premium": "💎 ASTREX Premium: Активен",
        "status_free": "🆓 Бесплатный тариф",
        "status_text": "Твой статус: {status}",
        "grant_usage": "⚠️ Использование: `/grant <user_id> <days>`",
        "grant_success": "✅ Подписка на {days} дн. успешно выдана пользователю `{user_id}`",
        "grant_error_num": "❌ Ошибка: ID и дни должны быть числами.",
        "grant_error_gen": "❌ Произошла ошибка: {e}",
        "lang_select": "Выберите язык / Select language:",
        "lang_changed": "Язык изменен на Русский! 🇷🇺",
        "morning_header": "✨ Доброе утро{name}! Твоё послание на сегодня:\n\n",
        "afternoon_header": "✨ Добрый день{name}! Твоё послание на сегодня:\n\n",
        "premium_notif": "🎉 ASTREX Premium начислен!\n\nАдминистрация подарила тебе подписку на {days} дней, так как сейчас бот работает в тестовом режиме и могут встречаться технические неполадки. Пользуйся с удовольствием! ✨",
        "not_specified": "Не указано",
        "friend": "друг",
        "cmd_start": "🏠 Главный экран",
        "cmd_personalize": "⚙️ Настроить профиль",
        "cmd_subscription": "💎 Управление подпиской",
        "cmd_about": "✨ О проекте ASTREX",
        "cmd_help": "🆘 Помощь и поддержка",
        "btn_admin_stats": "📊 Статистика",
        "btn_admin_reload": "🔄 Перезагрузить",
        "btn_admin_grant": "🎁 Выдать подписку",
        "btn_tarot": "🃏 Карта дня",
        "tarot_shuffling": "🎴 *Тасую колоду...* \nПрислушиваюсь к энергиям Вселенной...",
        "tarot_header": "🃏 *Твоя карта дня:* {name} ({position})",
        "tarot_pos_upright": "Прямое положение",
        "tarot_pos_reversed": "Перевернутое положение",
        "tarot_already_pulled": "✨ Ты уже открывал(а) свою карту дня сегодня! Давай вспомним её послание: ✨",
        "announcement_new_feature": "✨ Рады сообщить, что в ASTREX появилась новая функция — **Карта дня (Таро)**! 🃏\n\nКаждый день вы можете получить персональное предсказание и мудрое послание от Вселенной. Попробуйте прямо сейчас, нажав на кнопку в меню! ✨",
        "btn_tarot_explanation": "🔍 Подробное разъяснение",
        "tarot_premium_only": "✨ Эта функция доступна только в **Premium-подписке**. Оформи её, чтобы получать глубокое толкование каждой карты! ✨",
        "evening_feedback": "✨ Вечер добрый, {name}! Понравилось ли тебе то, как прошел сегодняшний день после утреннего послания от Вселенной? ✨\n\nОцени свои ощущения от 1 до 5:",
        "feedback_thanks": "Благодарю за обратную связь! 🙏 Твои ответы помогают Вселенной лучше слышать тебя. ✨",
        "personalization_configured": "✨ Твой профиль настроен:\n\n📅 **Дата**: {date} ({zodiac})\n⏰ **Время**: {time}\n🌍 **Регион**: {region}",
        "btn_edit_data": "📝 Изменить данные",
        "btn_cancel": "🔙 Отмена",
        "personalization_start": "Давай настроим твой профиль, чтобы послания были еще точнее! ✨\n\nВведи свою дату рождения (например: 01.01.1990):",
        "data_deleted": "✅ Данные удалены.",
        "delete_error": "Ошибка при удалении данных.",
    },
    "en": {
        "start_greeting": "Hello, {name}! 👋\n\nI am your guide to the world of messages from the Universe.\nClick the button below to find out what the Universe wants to tell you today. ✨",
        "btn_get_message": "✨ Get Message",
        "btn_personalization": "⚙️ Personalization",
        "btn_subscription": "💎 Subscription",
        "btn_about": "✨ About",
        "btn_help": "🆘 Help",
        "btn_language": "🌐 Language / Язык",
        "btn_open_app": "🚀 Open Mini App",
        "already_received_premium": "✨{name}, you've already received your message for today:\n\n",
        "already_received_free": "🌌{name}, you have already received your message for today. Come back tomorrow for a new one! ✨\n\n",
        "message_header": "✨{name}, your message for today:\n\n",
        "btn_clarify": "🔍 Clarify Message",
        "clarify_header": "💡 *Explanation:*\n\n",
        "clarify_error": "Error getting explanation.",
        "tarot_load_error": "Error loading Tarot data.",
        "tarot_card_not_found": "Error: card data not found.",
        "tarot_exp_soon": "Explanation for this card will appear soon! ✨",
        "delete_error": "Error deleting data.",
        "action_cancelled": "Action cancelled.",
        "main_menu": "Main Menu:",
        "zodiac_aries": "Aries", "zodiac_taurus": "Taurus", "zodiac_gemini": "Gemini", "zodiac_cancer": "Cancer",
        "zodiac_leo": "Leo", "zodiac_virgo": "Virgo", "zodiac_libra": "Libra", "zodiac_scorpio": "Scorpio",
        "zodiac_sagittarius": "Sagittarius", "zodiac_capricorn": "Capricorn", "zodiac_aquarius": "Aquarius", "zodiac_pisces": "Pisces",
        "ask_time": "Great! You are a **{zodiac}**! 🌟\n\nNow enter your time of birth (e.g., 12:00 or 'don't know'):",
        "ask_region": "And finally: specify the region or city where you were born:",
        "data_saved": "Your data has been successfully saved! 🌟\n Now I know you a little better.",
        "sub_active": "🌟 You already have an ASTREX Premium subscription!\n\nIt will be active for {days} more days.\nThank you for being with us! ✨",
        "sub_not_active": "Click the button below to proceed to payment via PayPal ✨",
        "payment_success": "Thank you for the payment notification! 🎉\nYour ASTREX Premium subscription has been activated for 30 days.\nWe will check the transaction shortly.",
        "about_text": "✨ *ASTREX* is your personal guide in the world of metaphysics and self-discovery.\n\nWe combine ancient knowledge of planetary movement, numbers, and centuries-old traditions with modern technology to give you inspiration every day.\n\nOur bot will help you:\n• Receive daily messages from the Universe\n• Deepen your understanding of your nature through personalized forecasts\n• Find answers to important questions at the right moment\n\nMay every star shine just for you! 🌟",
        "help_text": "🆘 *Need help?*\n\nIf you have problems with your subscription or questions about the bot, write to our support team:\n\n📩 [Contact Support](https://t.me/astrexbotfather)\n\nWe will definitely help! ✨",
        "status_premium": "💎 ASTREX Premium: Active",
        "status_free": "🆓 Free Tier",
        "status_text": "Your status: {status}",
        "grant_usage": "⚠️ Usage: `/grant <user_id> <days>`",
        "grant_success": "✅ Subscription for {days} days has been successfully granted to user `{user_id}`",
        "grant_error_num": "❌ Error: ID and days must be numbers.",
        "grant_error_gen": "❌ An error occurred: {e}",
        "lang_select": "Select language / Выберите язык:",
        "lang_changed": "Language changed to English! 🇺🇸",
        "morning_header": "✨ Good morning{name}! Your message for today:\n\n",
        "afternoon_header": "✨ Good afternoon{name}! Your message for today:\n\n",
        "premium_notif": "🎉 ASTREX Premium granted!\n\nThe administration has gifted you a subscription for {days} days because the bot is currently in test mode and technical issues may occur. Enjoy! ✨",
        "not_specified": "Not specified",
        "friend": "friend",
        "cmd_start": "🏠 Main Screen",
        "cmd_personalize": "⚙️ Configure Profile",
        "cmd_subscription": "💎 Manage Subscription",
        "cmd_about": "✨ About ASTREX",
        "cmd_help": "🆘 Help & Support",
        "btn_admin_stats": "📊 Stats",
        "btn_admin_reload": "🔄 Reload Cache",
        "btn_admin_grant": "🎁 Grant Sub",
        "btn_tarot": "🃏 Card of the Day",
        "tarot_shuffling": "🎴 *Shuffling the deck...* \nListening to the Universe's energies...",
        "tarot_header": "🃏 *Your card of the day:* {name} ({position})",
        "tarot_pos_upright": "Upright",
        "tarot_pos_reversed": "Reversed",
        "tarot_already_pulled": "✨ You've already pulled your card of the day today! Let's recall its message: ✨",
        "announcement_new_feature": "✨ We are excited to announce a new feature in ASTREX — **Card of the Day (Tarot)**! 🃏\n\nEvery day you can receive a personal prediction and a wise message from the Universe. Try it now by clicking the button in the menu! ✨",
        "btn_tarot_explanation": "🔍 Detailed Explanation",
        "tarot_premium_only": "✨ This feature is only available with a **Premium subscription**. Subscribe to receive deep interpretations of each card! ✨",
        "evening_feedback": "✨ Good evening, {name}! How did your day go after receiving the morning message from the Universe? ✨\n\nRate your sensations from 1 to 5:",
        "feedback_thanks": "Thank you for your feedback! 🙏 Your answers help the Universe hear you better. ✨",
        "personalization_configured": "✨ Your profile is configured:\n\n📅 **Date**: {date} ({zodiac})\n⏰ **Time**: {time}\n🌍 **Region**: {region}",
        "btn_edit_data": "📝 Edit Data",
        "btn_cancel": "🔙 Cancel",
        "personalization_start": "Let's set up your profile to make the messages even more accurate! ✨\n\n Please enter your date of birth (e.g., 01.01.1990):",
        "data_deleted": "✅ Data deleted.",
        "delete_error": "Error deleting data.",
    },
    "ka": {
        "start_greeting": "გამარჯობა, {name}! 👋\n\nმე ვარ შენი გზამკვლევი სამყაროს შეტყობინებების სამყაროში.\nდააჭირე ქვედა ღილაკს, რომ გაიგო, რისი თქმა სურს სამყაროს შენთვის დღეს. ✨",
        "main_menu": "მთავარი მენიუ:",
        "btn_get_message": "✨ მიიღე შეტყობინება",
        "btn_subscription": "💎 გამოწერა",
        "btn_personalization": "⚙️ პერსონალიზაცია",
        "btn_about": "✨ პროექტის შესახებ",
        "btn_help": "🆘 დახმარება",
        "btn_language": "🌐 ენა / Language / Язык",
        "btn_open_app": "🚀 Mini App-ის გახსნა",
        "message_header": "✨ {name}, შენი შეტყობინება დღეს:\n\n",
        "already_received_free": "✨ {name}, შენ უკვე მიიღე დღევანდელი შეტყობინება:\n\n",
        "already_received_premium": "✨ {name}, შენი პრემიუმ შეტყობინება დღეს:\n\n",
        "status_text": "📊 შენი სტატუსი: {status}",
        "status_free": "უფასო",
        "status_premium": "პრემიუმი 💎",
        "about_text": "*ASTREX* — ეს არის პროექტი შენი შინაგანი სამყაროსა და სამყაროს ენერგიებთან დასაკავშირებლად.\n\nყოველდღე შენ იღებ უნიკალურ შეტყობინებას, რომელიც დაგეხმარება იპოვო პასუხები მნიშვნელოვან კითხვებზე და იგრძნო მხარდაჭერა შენს გზაზე. ✨",
        "help_text": "🆘 *დახმარება და მხარდაჭერა*\n\nგაქვს კითხვები ან შემოთავაზებები? მოგვწერე: @support_astrex\n\n*ხელმისაწვდომი ბრძანებები:*\n/start — ბოტის გადატვირთვა\n/message — შეტყობინების მიღება\n/personalize — პროფილის პარამეტრები\n/subscription — გამოწერის მართვა",
        "sub_active": "✅ გამოწერა აქტიურია!\n\nდარჩენილია: {days} დღე.",
        "sub_not_active": "❌ გამოწერა არ არის აქტიური.\n\nმიიღე წვდომა პერსონალიზებულ და დეტალურ შეტყობინებებზე გამოწერის გაფორმებით! ✨",
        "payment_success": "✅ გადახდა წარმატებულია! გამოწერა გააქტიურებულია. ✨",
        "ask_time": "ახლა შეიყვანე დაბადების დრო (მაგალითად, 14:30):",
        "ask_region": "და ბოლოს, დაბადების ადგილი (ქალაქი ან რეგიონი):",
        "data_saved": "✅ მონაცემები შენახულია! ახლა შენი შეტყობინებები კიდევ უფრო ზუსტი იქნება. ✨",
        "data_deleted": "✅ მონაცემები წაშლილია.",
        "delete_error": "შეცდომა მონაცემების წაშლისას.",
        "action_cancelled": "მოქმედება გაუქმებულია.",
        "ask_date": "გთხოვთ, შეიყვანოთ დაბადების თარიღი (მაგალითად, 01.01.1990):",
        "lang_select": "აირჩიეთ ენა / Select language / Выберите язык:",
        "lang_changed": "ენა შეიცვალა! 🇬🇪",
        "morning_header": "✨ დილა მშვიდობისა{name}! შენი შეტყობინება დღეს:\n\n",
        "afternoon_header": "✨ მოგესალმებით{name}! შენი შეტყობინება დღეს:\n\n",
        "premium_notif": "🎉 ASTREX Premium დაგერიცხათ!\n\nადმინისტრაციამ მოგცათ გამოწერა {days} დღით, რადგან ბოტი ამჟამად მუშაობს ტესტურ რეჟიმში და შესაძლოა წარმოიშვას ტექნიკური პრობლემები. ისარგებლეთ სიამოვნებით! ✨",
        "not_specified": "არ არის მითითებული",
        "friend": "მეგობარო",
        "cmd_start": "🏠 მთავარი ეკრანი",
        "cmd_personalize": "⚙️ პროფილის დაყენება",
        "cmd_subscription": "💎 გამოწერის მართვა",
        "cmd_about": "✨ ASTREX-ის შესახებ",
        "cmd_help": "🆘 დახმარება და მხარდაჭერა",
        "btn_admin_stats": "📊 სტატისტიკა",
        "btn_admin_reload": "🔄 გადატვირთვა",
        "btn_admin_grant": "🎁 გამოწერის გაცემა",
        "btn_clarify": "🔍 შეტყობინების განმარტება",
        "clarify_header": "💡 *განმარტება:*\n\n",
        "clarify_error": "შეცდომა განმარტების მიღებისას.",
        "tarot_load_error": "შეცდომა ტაროს მონაცემების ჩატვირთვისას.",
        "tarot_card_not_found": "შეცდომა: ბარათის მონაცემები ვერ მოიძებნა.",
        "tarot_exp_soon": "ამ ბარათის განმარტება მალე გამოჩნდება! ✨",
        "grant_usage": "⚠️ გამოყენება: `/grant <user_id> <days>`",
        "grant_success": "✅ {days} დღიანი გამოწერა გააქტიურებულია მომხმარებლისთვის {user_id}.",
        "grant_error_num": "❌ დღეების რაოდენობა უნდა იყოს რიცხვი.",
        "grant_error_gen": "❌ შეცდომა გამოწერის გააქტიურებისას: {e}",
        "zodiac_aries": "ვერძი", "zodiac_taurus": "კურო", "zodiac_gemini": "ტყუპები", "zodiac_cancer": "კირჩხიბი",
        "zodiac_leo": "ლომი", "zodiac_virgo": "ქალწული", "zodiac_libra": "სასწორი", "zodiac_scorpio": "ღრიანკალი",
        "zodiac_sagittarius": "მშვილდოსანი", "zodiac_capricorn": "თხის რქა", "zodiac_aquarius": "მერწყული", "zodiac_pisces": "თევზები",
        "personalization_configured": "✨ თქვენი პროფილი დაყენებულია:\n\n📅 **თარიღი**: {date} ({zodiac})\n⏰ **დრო**: {time}\n🌍 **რეგიონი**: {region}",
        "btn_edit_data": "📝 მონაცემების შეცვლა",
        "btn_cancel": "🔙 გაუქმება",
        "personalization_start": "მოდით დავაყენოთ თქვენი პროფილი, რათა შეტყობინებები კიდევ უფრო ზუსტი იყოს! ✨\n\nგთხოვთ, შეიყვანოთ თქვენი დაბადების თარიღი (მაგალითად, 01.01.1990):",
        "evening_feedback": "✨ საღამო მშვიდობისა, {name}! როგორ ჩაიარა თქვენმა დღემ სამყაროს დილის შეტყობინების შემდეგ? ✨\n\nშეაფასეთ თქვენი შეგრძნებები 1-დან 5-მდე:",
        "feedback_thanks": "გმადლობთ გამოხმაურებისთვის! 🙏 თქვენი პასუხები ეხმარება სამყაროს უკეთესად მოგისმინოთ. ✨",
        "btn_tarot": "🃏 დღის ბარათი",
        "tarot_shuffling": "🎴 *ბარათების არევა...* \nვუსმენთ სამყაროს ენერგიებს...",
        "tarot_header": "🃏 *თქვენი დღის ბარათი:* {name} ({position})",
        "tarot_pos_upright": "პირდაპირი პოზიცია",
        "tarot_pos_reversed": "ამობრუნებული პოზიცია",
        "tarot_already_pulled": "✨ თქვენ უკვე გაჩერეთ თქვენი დღის ბარათი დღეს! მოდით გავიხსენოთ მისი შეტყობინება: ✨",
        "announcement_new_feature": "✨ მოხარული ვართ გაცნობოთ, რომ ASTREX-ში დაემატა ახალი ფუნქცია — **დღის ბარათი (ტარო)**! 🃏\n\nყოველდღე შეგიძლიათ მიიღოთ პერსონალური პროგნოზი და ბრძნული გზავნილი სამყაროდან. სცადეთ ახლავე მენიუში ღილაკზე დაჭერით! ✨",
        "btn_tarot_explanation": "🔍 დეტალური განმარტება",
        "tarot_premium_only": "✨ ეს ფუქნცია ხელმისაწვდომია მხოლოდ **Premium-გამოწერით**. გამოიწერეთ, რათათ მიიღოთ თითოეული ბარათის ღრმა განმარტება! ✨",
    }
}
